php:
  build: .
  ports:
   - "9000:80"
   - "443:443"
  volumes:
   - ./www:/var/www/html
  links:
   - db
db:
  image: mariadb:latest
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=root